version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    # install
    - run:
        name: install pyarxaas
        command: pip3 install --user .
    - run:
        name: install dependencies
        command: pip3 install --user -r requirements.txt
    # download and prepare code climate test reporter
    - run:
        name: download cc-test-reporter
        command: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run:
        name: authorize cc-test-reporter
        command: chmod +x ./cc-test-reporter
    - run:
        name: prepare cc-test-reporter
        command: ./cc-test-reporter before-build
    # run tests
    - run:
        name: run pytest
        command: python3 -m pytest --cov-report=xml --cov=pyarxaas
    # run code climate test reporter and upload
    - run:
        name: run cc-test-reporter and upload result
        command: ./cc-test-reporter -d after-build
  deploy:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    # install dependencies
    - run:
        name: install twine
        command: pip3 install --user twine
    # build
    - run:
        name: build project
        command: python3 setup.py sdist bdist_wheel
    # deploy to pypi
    - run:
        name: deploy to pypi
        command: python3 -m twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
workflows:
 version: 2
 build_and_release:
   jobs:
     - build:
         filters:
           tags:
             ignore: /.*/
     - deploy:
         filters:
           tags:
             only: /[0-9](\.[0-9]+)(\.[0-9]+)/
           branches:
             ignore: /.*/
