name: Deploy to PyPI

on:
  release:
    types: [published]
env:
  TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
  TWINE_PASSWORD:  ${{secrets.PYPI_PASSWORD}}

jobs:

  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
    # install dependencies
      - name: install twine
        run: pip3 install --user twine
      - name: install wheel
        run: pip3 install --user wheel
    # build
      - name: build project
        run: python3 setup.py sdist bdist_wheel
    # deploy to pypi
      - name: deploy to pypi
        run: python3 -m twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*